"""The :class:`MDDB` class: filesystem + git + SQLite orchestration for the public verbs."""

from __future__ import annotations

import os
import subprocess
import sys
import uuid
from copy import deepcopy
from dataclasses import dataclass
from pathlib import Path

import yaml as pyyaml

from . import index
from .card import Card, slugify


@dataclass
class _Staged:
    card: Card | None
    original_relpath: str | None
    relpath: str | None


def _copy(card: Card) -> Card:
    return Card(yaml=deepcopy(card.yaml), body=card.body)


def _resolve_relpath(relpath: str | None, title: str) -> str:
    """Resolve a caller-supplied relpath against the title for slug autofill.

    Rules:
        - ``relpath=None`` → ``<slugify(title)>.md`` (flat at root).
        - ``relpath`` ends with ``/`` → directory; append ``<slugify(title)>.md``.
        - ``relpath`` has no ``.md`` extension → append it.
        - Otherwise return ``relpath`` unchanged.
    """
    if relpath is None:
        return f"{slugify(title)}.md"
    if relpath.endswith("/"):
        return f"{relpath}{slugify(title)}.md"
    if not relpath.endswith(".md"):
        return f"{relpath}.md"
    return relpath


class MDDB:
    def __init__(self, path: Path | str):
        """Open an existing mddb at ``path`` or initialise a fresh one in place.

        If ``path/.git`` exists the directory is treated as an existing mddb
        root and opened. Otherwise ``path`` is created (``mkdir -p``), ``git
        init`` is run, a ``.gitignore`` containing ``*.tmp`` is committed,
        and a one-line notice is printed to stderr so a typoed path is
        visible before any data is written.

        Args:
            path: Filesystem path to the mddb directory. ``~`` is expanded
                and the path is resolved to an absolute form.

        Raises:
            subprocess.CalledProcessError: ``git`` is not installed or fails
                during initialisation.
        """
        self.root = Path(path).expanduser().resolve()
        if not (self.root / ".git").exists():
            self.root.mkdir(parents=True, exist_ok=True)
            self._init_git()
            print(f"mddb: initialised new mddb at {self.root}", file=sys.stderr)
        self.conn = index.open_index(self.root)
        self._active_tx: Transaction | None = None

    def create(
        self,
        *,
        title: str,
        summary: str,
        yaml: dict | None = None,
        body: str = "",
        rationale: str,
        relpath: str | None = None,
    ) -> Card:
        """Create a new card on disk, in git, and in the index.

        ``title`` and ``summary`` are mandatory kwargs because both are
        substrate-privileged disclosure keys (see CLAUDE.md "Progressive
        disclosure"). The title also drives the default file slug.

        Args:
            title: Human-readable name; also drives ``relpath`` slug if
                ``relpath`` is ``None`` or ends with ``/``.
            summary: One-paragraph headline; surfaces in :meth:`list`.
            yaml: Other frontmatter as a Python dict. ``title``, ``summary``,
                and an autogenerated ``id`` (UUIDv4 if absent) are added in
                addition.
            body: Markdown body. Empty by default.
            relpath: Path relative to the mddb root. Three forms accepted:
                ``None`` → ``<slugify(title)>.md`` (flat root);
                ``"inventory/"`` (trailing slash) → directory + slug autofill;
                ``"inventory/fridge"`` or ``"inventory/fridge.md"`` →
                explicit filename (``.md`` appended if missing).
            rationale: Git commit message. Required, non-empty.

        Returns:
            The created :class:`Card` with ``id``, ``title``, ``summary``
            populated.

        Raises:
            FileExistsError: ``relpath`` already exists in the working tree.
            ValueError: ``relpath`` is absolute, contains ``..``, or otherwise
                invalid after resolution.
            subprocess.CalledProcessError: ``git add`` or ``git commit``
                failed.
        """
        if self._active_tx is not None:
            raise RuntimeError(
                "cannot use base MDDB.create while a transaction is active; use tx.create instead"
            )
        yaml = dict(yaml or {})
        yaml["title"] = title
        yaml["summary"] = summary
        if "id" not in yaml:
            yaml["id"] = str(uuid.uuid4())
        card = Card(yaml=yaml, body=body)
        relpath = _resolve_relpath(relpath, title)
        self._validate_relpath(relpath)
        target = self.root / relpath
        if target.exists():
            raise FileExistsError(relpath)
        target.parent.mkdir(parents=True, exist_ok=True)
        self._write_atomic(target, str(card))
        self._git("add", "--", relpath)
        self._git("commit", "-m", rationale)
        with self.conn:
            cur = self.conn.execute(
                "INSERT INTO entries(id, relpath, yaml_text, body) VALUES (?, ?, ?, ?)",
                (
                    card.id,
                    relpath,
                    pyyaml.safe_dump(card.yaml, sort_keys=False, allow_unicode=True),
                    card.body,
                ),
            )
            index.index_fields(self.conn, cur.lastrowid, card.yaml)
        return card

    def read(self, card_id: str) -> Card:
        """Read a card by id, returning a fresh :class:`Card` from disk.

        Resolves the card's relpath via the index, then loads the file
        directly (the SQLite copy is not used for reads). Mutate the
        returned card and pass it to :meth:`update` to persist changes.

        Args:
            card_id: The card's ``id`` (the value at ``yaml["id"]``).

        Returns:
            The :class:`Card` as parsed from its current file.

        Raises:
            KeyError: No card with that ``id`` is known to the index.
            FileNotFoundError: The index points at a path that no longer
                exists on disk.
        """
        return Card.from_file(self.root / self._relpath(card_id))

    def update(self, card: Card, *, summary: str, rationale: str) -> Card:
        """Persist mutations to ``card`` back to disk, git, and the index.

        ``summary`` is a mandatory kwarg so the caller is forced to make a
        deliberate decision at every mutation: pass the existing summary
        unchanged (acknowledging it's still accurate) or pass a new one
        (re-summarising). The kwarg overwrites ``card.yaml["summary"]`` —
        whatever string the caller passes becomes the authoritative new
        summary on disk.

        Resolves the file via ``card.id`` (the value at
        ``card.yaml["id"]``), rewrites the file from ``str(card)``, commits
        with ``rationale``, then refreshes the index row + entry_fields.

        The id is effectively immutable: do not mutate ``card.yaml["id"]``
        between read and update — the lookup will fail with ``KeyError``
        because the new id is not in the index. To change a card's
        location, use :meth:`move`.

        Args:
            card: The :class:`Card` to write back. Its ``yaml`` and ``body``
                are persisted; ``yaml["id"]`` must match the value used at
                read time.
            summary: New (or unchanged) one-paragraph summary. Overwrites
                ``card.yaml["summary"]``.
            rationale: Git commit message. Required, non-empty.

        Returns:
            The same ``card`` (for chaining).

        Raises:
            KeyError: ``card.yaml["id"]`` is not in the index.
            subprocess.CalledProcessError: ``git add`` or ``git commit``
                failed.
        """
        if self._active_tx is not None:
            raise RuntimeError(
                "cannot use base MDDB.update while a transaction is active; use tx.update instead"
            )
        card.yaml["summary"] = summary
        relpath = self._relpath(card.id)
        self._write_atomic(self.root / relpath, str(card))
        self._git("add", "--", relpath)
        self._git("commit", "-m", rationale)
        with self.conn:
            rowid = self.conn.execute(
                "SELECT rowid FROM entries WHERE id = ?", (card.id,)
            ).fetchone()[0]
            self.conn.execute(
                "UPDATE entries SET yaml_text = ?, body = ? WHERE rowid = ?",
                (
                    pyyaml.safe_dump(card.yaml, sort_keys=False, allow_unicode=True),
                    card.body,
                    rowid,
                ),
            )
            self.conn.execute(
                "DELETE FROM entry_fields WHERE entry_rowid = ?", (rowid,)
            )
            index.index_fields(self.conn, rowid, card.yaml)
        return card

    def delete(self, card_id: str, *, rationale: str) -> None:
        """Remove a card from the working tree, git, and the index.

        The deletion is committed (``git rm`` + ``git commit``) so the
        card's history is recoverable via ``git show <sha>:<relpath>`` for
        any commit before this one.

        Args:
            card_id: The card's ``id``.
            rationale: Git commit message. Required, non-empty.

        Raises:
            KeyError: No card with that ``id`` is known to the index.
            subprocess.CalledProcessError: ``git rm`` or ``git commit``
                failed.
        """
        if self._active_tx is not None:
            raise RuntimeError(
                "cannot use base MDDB.delete while a transaction is active; use tx.delete instead"
            )
        relpath = self._relpath(card_id)
        self._git("rm", "--", relpath)
        self._git("commit", "-m", rationale)
        with self.conn:
            self.conn.execute("DELETE FROM entries WHERE id = ?", (card_id,))

    def move(self, card_id: str, new_relpath: str, *, rationale: str) -> None:
        """Rename a card's file. The id is preserved so history follows.

        Uses ``git mv`` so a single commit records the rename (and
        :meth:`history` can follow it via ``git log --follow``). The card's
        ``id`` and contents are unchanged; only ``new_relpath`` differs.

        Args:
            card_id: The card's ``id``.
            new_relpath: Target path relative to the mddb root. Must be
                relative, end in ``.md``, and not contain ``..``.
            rationale: Git commit message. Required, non-empty.

        Raises:
            KeyError: No card with that ``id`` is known to the index.
            ValueError: ``new_relpath`` is invalid.
            subprocess.CalledProcessError: ``git mv`` or ``git commit``
                failed (e.g. target path already exists).
        """
        if self._active_tx is not None:
            raise RuntimeError(
                "cannot use base MDDB.move while a transaction is active; use tx.move instead"
            )
        old = self._relpath(card_id)
        self._validate_relpath(new_relpath)
        (self.root / new_relpath).parent.mkdir(parents=True, exist_ok=True)
        self._git("mv", "--", old, new_relpath)
        self._git("commit", "-m", rationale)
        with self.conn:
            self.conn.execute(
                "UPDATE entries SET relpath = ? WHERE id = ?", (new_relpath, card_id)
            )

    def list(self) -> list[dict]:
        """Return every card's id, title, and summary — the progressive-disclosure summary view.

        Cheap to call: pulls only the three substrate-privileged keys from
        the SQLite cache (no body, no YAML parse). Use :meth:`read` for the
        full card once a caller has decided which one to open.

        Returns:
            A list of ``{"id": str, "title": str | None, "summary": str | None}``
            dicts, one per card. ``title`` and ``summary`` come back as
            ``None`` for cards missing those keys.
        """
        rows = self.conn.execute(
            "SELECT entries.id, t.value_str, s.value_str FROM entries "
            "LEFT JOIN entry_fields t ON t.entry_rowid = entries.rowid AND t.key = 'title' "
            "LEFT JOIN entry_fields s ON s.entry_rowid = entries.rowid AND s.key = 'summary'"
        ).fetchall()
        return [
            {"id": cid, "title": title, "summary": summary}
            for cid, title, summary in rows
        ]

    def history(self, card_id: str) -> list[dict]:
        """Return the commit history of a card, newest first.

        Uses ``git log --follow`` so commits from before any :meth:`move`
        are included.

        Args:
            card_id: The card's ``id``.

        Returns:
            A list of dicts, newest first. Each dict has:

            - ``sha`` (str): full commit SHA.
            - ``author`` (str): commit author name.
            - ``timestamp`` (str): ISO-8601 author date.
            - ``message`` (str): full commit message body (the
              ``rationale`` passed to the mutating verb).

        Raises:
            KeyError: No card with that ``id`` is known to the index.
            subprocess.CalledProcessError: ``git log`` failed.
        """
        relpath = self._relpath(card_id)
        out = self._git(
            "log",
            "--follow",
            "--pretty=format:%H%x00%an%x00%aI%x00%B%x1e",
            "--",
            relpath,
        ).stdout
        commits = []
        for chunk in out.split("\x1e"):
            chunk = chunk.strip("\n")
            if not chunk:
                continue
            sha, author, ts, message = chunk.split("\x00", 3)
            commits.append(
                {"sha": sha, "author": author, "timestamp": ts, "message": message}
            )
        return commits

    def transaction(self, *, rationale: str) -> Transaction:
        """Open a batching context manager. See :class:`Transaction`."""
        return Transaction(self, rationale)

    def _relpath(self, card_id: str) -> str:
        row = self.conn.execute(
            "SELECT relpath FROM entries WHERE id = ?", (card_id,)
        ).fetchone()
        if row is None:
            raise KeyError(card_id)
        return row[0]

    def _write_atomic(self, target: Path, text: str) -> None:
        tmp = target.with_suffix(target.suffix + f".{uuid.uuid4().hex}.tmp")
        tmp.write_text(text)
        os.replace(tmp, target)

    def _init_git(self) -> None:
        subprocess.run(["git", "init", "-q", "-b", "master"], cwd=self.root, check=True)
        (self.root / ".gitignore").write_text("*.tmp\n")
        self._git("add", "--", ".gitignore")
        self._git("commit", "-m", "initial commit")

    def _git(self, *args: str) -> subprocess.CompletedProcess:
        return subprocess.run(
            ["git", *args], cwd=self.root, check=True, capture_output=True, text=True
        )

    def _validate_relpath(self, relpath: str) -> None:
        if not relpath.endswith(".md"):
            raise ValueError(f"relpath must end in .md: {relpath}")
        p = Path(relpath)
        if p.is_absolute() or ".." in p.parts:
            raise ValueError(f"invalid relpath: {relpath}")


class Transaction:
    """Buffer create/read/update/delete/move operations and materialise them as one commit on clean exit.

    Construct via :meth:`MDDB.transaction`. Operations are staged in memory
    until the ``with`` block exits cleanly; on body exception, nothing is
    written. On clean exit with a non-empty buffer, the entire batch is
    materialised as a single git commit and a single SQLite transaction.

    A ``Transaction`` is single-shot — after ``__exit__`` (clean or not),
    further verb calls and re-entry both raise ``RuntimeError``.
    """

    def __init__(self, db: MDDB, rationale: str):
        self._db = db
        self._rationale = rationale
        self._staged: dict[str, _Staged] = {}
        self._relpaths: dict[str, str] = {}
        self._closed = False

    def __enter__(self) -> Transaction:
        if self._closed:
            raise RuntimeError("transaction already closed")
        if self._db._active_tx is not None:
            raise RuntimeError("nested transactions are not supported")
        self._db._active_tx = self
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        try:
            if exc_type is None and self._staged:
                self._commit()
        finally:
            self._db._active_tx = None
            self._closed = True

    def create(
        self,
        *,
        title: str,
        summary: str,
        yaml: dict | None = None,
        body: str = "",
        relpath: str | None = None,
    ) -> Card:
        """Stage a new card for creation. Materialises on clean ``__exit__``."""
        if self._closed:
            raise RuntimeError("transaction already closed")
        yaml_d = dict(yaml or {})
        yaml_d["title"] = title
        yaml_d["summary"] = summary
        if "id" not in yaml_d:
            yaml_d["id"] = str(uuid.uuid4())
        new_card = Card(yaml=yaml_d, body=body)
        resolved = _resolve_relpath(relpath, title)
        self._db._validate_relpath(resolved)
        new_id = new_card.id
        if new_id in self._staged:
            raise RuntimeError(f"duplicate id in transaction: {new_id}")
        row = self._db.conn.execute(
            "SELECT 1 FROM entries WHERE id = ?", (new_id,)
        ).fetchone()
        if row is not None:
            raise RuntimeError(f"id already exists: {new_id}")
        if resolved in self._relpaths:
            raise FileExistsError(resolved)
        if (self._db.root / resolved).exists() and not self._staged_delete_at(resolved):
            raise FileExistsError(resolved)
        self._staged[new_id] = _Staged(
            card=new_card, original_relpath=None, relpath=resolved
        )
        self._relpaths[resolved] = new_id
        return _copy(new_card)

    def read(self, card_id: str) -> Card:
        """Read a card with staged-state visibility."""
        if self._closed:
            raise RuntimeError("transaction already closed")
        staged = self._staged.get(card_id)
        if staged is not None:
            if staged.card is None and staged.relpath is None:
                raise KeyError(card_id)
            if staged.card is not None:
                return _copy(staged.card)
            return _copy(self._db.read(card_id))
        return self._db.read(card_id)

    def update(self, card: Card, *, summary: str) -> Card:
        """Stage an update to ``card``. Caller's ``Card`` is deep-copied before staging."""
        if self._closed:
            raise RuntimeError("transaction already closed")
        card.yaml["summary"] = summary
        card_id = card.id
        staged = self._staged.get(card_id)
        if staged is not None and staged.card is None and staged.relpath is None:
            raise KeyError(card_id)
        staged_card = _copy(card)
        if staged is None:
            original = self._db._relpath(card_id)
            self._staged[card_id] = _Staged(
                card=staged_card, original_relpath=original, relpath=original
            )
            self._relpaths[original] = card_id
        else:
            self._staged[card_id] = _Staged(
                card=staged_card,
                original_relpath=staged.original_relpath,
                relpath=staged.relpath,
            )
        return _copy(card)

    def delete(self, card_id: str) -> None:
        """Stage a delete of ``card_id``."""
        if self._closed:
            raise RuntimeError("transaction already closed")
        staged = self._staged.get(card_id)
        if staged is not None and staged.card is None and staged.relpath is None:
            raise KeyError(card_id)
        if staged is not None and staged.original_relpath is None:
            del self._staged[card_id]
            if (
                staged.relpath is not None
                and self._relpaths.get(staged.relpath) == card_id
            ):
                del self._relpaths[staged.relpath]
            return
        if staged is not None:
            if (
                staged.relpath is not None
                and self._relpaths.get(staged.relpath) == card_id
            ):
                del self._relpaths[staged.relpath]
            self._staged[card_id] = _Staged(
                card=None, original_relpath=staged.original_relpath, relpath=None
            )
            return
        original = self._db._relpath(card_id)
        self._staged[card_id] = _Staged(
            card=None, original_relpath=original, relpath=None
        )

    def move(self, card_id: str, new_relpath: str) -> None:
        """Stage a relpath change for ``card_id``."""
        if self._closed:
            raise RuntimeError("transaction already closed")
        self._db._validate_relpath(new_relpath)
        staged = self._staged.get(card_id)
        if staged is not None and staged.card is None and staged.relpath is None:
            raise KeyError(card_id)
        if staged is not None:
            current = staged.relpath
        else:
            current = self._db._relpath(card_id)
        if new_relpath == current:
            return
        owner = self._relpaths.get(new_relpath)
        if owner is not None and owner != card_id:
            raise FileExistsError(new_relpath)
        if (self._db.root / new_relpath).exists():
            if staged is None or staged.original_relpath != new_relpath:
                raise FileExistsError(new_relpath)
        if staged is None:
            original = self._db._relpath(card_id)
            new_record = _Staged(
                card=None, original_relpath=original, relpath=new_relpath
            )
        elif staged.original_relpath is None:
            new_record = _Staged(
                card=staged.card, original_relpath=None, relpath=new_relpath
            )
        else:
            new_record = _Staged(
                card=staged.card,
                original_relpath=staged.original_relpath,
                relpath=new_relpath,
            )
        if current is not None and self._relpaths.get(current) == card_id:
            del self._relpaths[current]
        if (
            new_record.card is None
            and new_record.original_relpath is not None
            and new_record.relpath == new_record.original_relpath
        ):
            if card_id in self._staged:
                del self._staged[card_id]
            return
        self._staged[card_id] = new_record
        self._relpaths[new_relpath] = card_id

    def _staged_delete_at(self, path: str) -> bool:
        return any(
            s.original_relpath == path and s.card is None and s.relpath is None
            for s in self._staged.values()
        )

    def _commit(self) -> None:
        for staged in self._staged.values():
            if staged.card is None and staged.relpath is None:
                self._db._git("rm", "--", staged.original_relpath)
        for staged in self._staged.values():
            if (
                staged.original_relpath is not None
                and staged.relpath is not None
                and staged.relpath != staged.original_relpath
            ):
                (self._db.root / staged.relpath).parent.mkdir(
                    parents=True, exist_ok=True
                )
                self._db._git("mv", "--", staged.original_relpath, staged.relpath)
        for staged in self._staged.values():
            if staged.card is not None and staged.relpath is not None:
                target = self._db.root / staged.relpath
                target.parent.mkdir(parents=True, exist_ok=True)
                self._db._write_atomic(target, str(staged.card))
                self._db._git("add", "--", staged.relpath)
        self._db._git("commit", "-m", self._rationale)
        with self._db.conn:
            for card_id, staged in self._staged.items():
                if staged.card is None and staged.relpath is None:
                    self._db.conn.execute(
                        "DELETE FROM entries WHERE id = ?", (card_id,)
                    )
                    continue
                if (
                    staged.original_relpath is None
                    and staged.card is not None
                    and staged.relpath is not None
                ):
                    cur = self._db.conn.execute(
                        "INSERT INTO entries(id, relpath, yaml_text, body) VALUES (?, ?, ?, ?)",
                        (
                            staged.card.id,
                            staged.relpath,
                            pyyaml.safe_dump(
                                staged.card.yaml, sort_keys=False, allow_unicode=True
                            ),
                            staged.card.body,
                        ),
                    )
                    index.index_fields(self._db.conn, cur.lastrowid, staged.card.yaml)
                    continue
                rowid = self._db.conn.execute(
                    "SELECT rowid FROM entries WHERE id = ?", (card_id,)
                ).fetchone()[0]
                if staged.card is None:
                    self._db.conn.execute(
                        "UPDATE entries SET relpath = ? WHERE rowid = ?",
                        (staged.relpath, rowid),
                    )
                else:
                    self._db.conn.execute(
                        "UPDATE entries SET relpath = ?, yaml_text = ?, body = ? WHERE rowid = ?",
                        (
                            staged.relpath,
                            pyyaml.safe_dump(
                                staged.card.yaml, sort_keys=False, allow_unicode=True
                            ),
                            staged.card.body,
                            rowid,
                        ),
                    )
                    self._db.conn.execute(
                        "DELETE FROM entry_fields WHERE entry_rowid = ?", (rowid,)
                    )
                    index.index_fields(self._db.conn, rowid, staged.card.yaml)
